name: ggrm_mobile
description: "Flutter client to call the GGRM stock prediction backend"
version: 2.0.0+1
publish_to: 'none'
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.0.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  google_sign_in: ^6.2.1
  fl_chart: ^0.63.0
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
  flutter_animate: ^4.1.1
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon.png

